apiVersion: v1
kind: Service
metadata:
  name: jobvacancydb
  labels:
    app: jobvacancydb
spec:
  selector:
    app: jobvacancydb
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 5432
    type: NodePort
