apiVersion: v1
kind: Secret
metadata:
  name: jobvacancysecret
  labels:
    app: jobvacancy
stringData:
  POSTGRES_DB: jobvacancy
  POSTGRES_PASSWORD: "A COMPLETAR"
  DATABASE_URL: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
