version: '3'
services:
  app1:
    image: nicopaez/password-api
  app2:
    image: nicopaez/password-api
  nginx:
    image: nginx:1.22.0-alpine
    volumes:
      - .:/etc/nginx/conf.d/
    ports:
      - "5000:80"
    depends_on:
      - "app1"
      - "app2"